[package]
name = "flare"
description = "An unofficial Signal GTK client."
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Optimize matrix-sdk-store-encryption, as otherwise opening the store takes 6 seconds.
[profile.dev.package.matrix-sdk-store-encryption]
opt-level = 3
[profile.dev.package.sha2]
opt-level = 3

[dependencies]
gtk = { version = "0.6.6", package = "gtk4", features = ["v4_10"]}
gdk = { version = "0.6.3", package = "gdk4" }
libadwaita = { version = "0.4.4", features = ["v1_3"]}
ashpd = { version = "0.4.0", features = ["gtk4"]}
zbus = "3.14.1"

gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
 
futures = "0.3.28"
tokio = { version = "1.29.1", features = ["rt", "macros", "rt-multi-thread", "time"] }
regex = "1.9.1"
lazy_static = "1.4.0"

presage = { git = "https://github.com/whisperfish/presage", rev = "9337c5c" }
presage-store-sled = { git = "https://github.com/whisperfish/presage", rev = "9337c5c" }
libsignal-service = { git = "https://github.com/whisperfish/libsignal-service-rs", rev = "3c65765"  }

async-trait = "0.1.72"
sled = "0.34.7"
oo7 = { version = "0.1.2", default-features = false, features = ["native_crypto", "async-std"] }
rand = "0.8.5"
zeroize = "1.6.0"
hex = "0.4.3"
serde = "1.0"
serde_json = "1.0.103"
url = "2.4.0"
once_cell = "1.18.0"

qrcode-generator = "4.1.8"

log = "0.4.19"
env_logger = "0.10.0"

err-derive = "0.3.1"

tracing = { version = "0.1.37", features = ["log-always"] }

[features]
default = []
screenshot = []

[patch.crates-io]
"curve25519-dalek" = { git = 'https://github.com/Schmiddiii/curve25519-dalek', rev = '1b9f81352bb659999a46af961f069d635ca432d3' }

[patch."https://github.com/signalapp/curve25519-dalek"]
"curve25519-dalek" = { git = 'https://github.com/Schmiddiii/curve25519-dalek', rev = '1b9f81352bb659999a46af961f069d635ca432d3' }
