[package]
name = "flare"
description = "Chat with your friends on Signal"
authors = ["Julian Schmidhuber <mobile@schmidhuberj.de>"]
homepage = "https://mobile.schmidhuberj.de/flare"
repository = "https://gitlab.com/schmiddi-on-mobile/flare"
license = "AGPL-3.0-only"
version = "0.15.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Optimize presage-store-cipher, as otherwise opening the store takes 6 seconds.
[profile.dev.package.presage-store-cipher]
opt-level = 3
[profile.dev.package.sha2]
opt-level = 3

[dependencies]
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_12"]}
adw = { version = "0.7.0", package = "libadwaita", features = ["v1_5"]}
ashpd = { version = "0.9.1", default-features = false, features = [ "gtk4", "tokio" ]}
zbus = { version = "4.4.0", default-features = false, features = [ "tokio" ]}

gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
 
futures = "0.3.30"
tokio = { version = "1.38.1", features = ["rt", "macros", "rt-multi-thread", "time"] }
regex = "1.10.5"
lazy_static = "1.5.0"

presage = { git = "https://github.com/whisperfish/presage", rev = "b0e862baa03e452ccb9717d7d2f005ab93d46303" }
presage-store-sled = { git = "https://github.com/whisperfish/presage", rev = "b0e862baa03e452ccb9717d7d2f005ab93d46303" }
libsignal-service = { git = "https://github.com/whisperfish/libsignal-service-rs", rev = "f99ff8324378ea653dbd5aa0c5d55e4414b34e23" }

oo7 = { version = "0.3.3", default-features = false, features = ["native_crypto", "tokio"] }
rand = "0.8.5"
url = "2.5.2"
once_cell = "1.19.0"

qrcode-generator = "4.1.9"

log = "0.4.22"
env_logger = "0.11.3"

tracing = { version = "0.1.40", features = ["log-always"] }
sourceview5 = "0.9.0"
libspelling = "0.3.0"
blurhash = { git = "https://github.com/Schmiddiii/blurhash-rs", rev = "e1f9bdc1976bcc0f7dc725ac3b4fdaa6c6bdffd7", features = ["image", "gdk-pixbuf"] }
image = "0.24.9"
chrono = "0.4.38"

phonenumber = { version = "0.3", optional = true }

[features]
default = []
screenshot = [ "dep:phonenumber" ]
screenshot-setup = [ "screenshot" ]
libspelling = []

[patch.crates-io]
curve25519-dalek = { git = 'https://github.com/signalapp/curve25519-dalek', tag = 'signal-curve25519-4.1.3' }

[patch."https://github.com/whisperfish/libsignal-service-rs.git"]
libsignal-service = { git = "https://github.com/Schmiddiii/libsignal-service-rs", rev = "340caf1e931a862f9052eecf089667465b3819af" }
libsignal-service-hyper = { git = "https://github.com/Schmiddiii/libsignal-service-rs", rev = "340caf1e931a862f9052eecf089667465b3819af" }
