[package]
name = "flare"
description = "Chat with your friends on Signal"
authors = ["Julian Schmidhuber <mobile@schmidhuberj.de>"]
homepage = "https://mobile.schmidhuberj.de/flare"
repository = "https://gitlab.com/schmiddi-on-mobile/flare"
license = "AGPL-3.0-only"
version = "0.20.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.10.3", package = "gtk4", features = ["v4_12"]}
gio = { version = "0.21.5", features = ["v2_70"]}
adw = { version = "0.8.1", package = "libadwaita", features = ["v1_8"]}

gettext-rs = { version = "0.7.7", features = ["gettext-system"] }

futures = "0.3.31"
tokio = { version = "1.48.0", features = ["rt", "macros", "rt-multi-thread", "time"] }
regex = "1.12.2"
lazy_static = "1.5.0"

presage = { git = "https://github.com/Schmiddiii/presage", rev = "8b40a2d35c610d04cb155076d2f68295793b1e49", default-features = false }
presage-store-sqlite = { git = "https://github.com/Schmiddiii/presage", rev = "8b40a2d35c610d04cb155076d2f68295793b1e49", default-features = false}
libsignal-service = { git = "https://github.com/whisperfish/libsignal-service-rs", rev = "3d07d8df33482b2d191c075fdc2b750738a89384", default-features = false, features = ["phonenumber"] }

rand = "0.9.2"
dirs = "5"
url = "2.5.7"
once_cell = "1.21.3"

qrcode-generator = "5.0.0"

[target.'cfg(target_os = "linux")'.dependencies]
oo7 = { version = "0.5.0", default-features = false, features = ["native_crypto", "tokio"] }
ashpd = { version = "0.12.0", default-features = false, features = ["gtk4", "tokio"] }
zbus = { version = "5.12.0", default-features = false, features = ["tokio"] }

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2"
cacao = { version = "0.4.0-beta2", optional = true }
objc = { version = "0.2.7", optional = true }
objc_id = { version = "0.1.1", optional = true }
hex = "0.4"

log = "0.4.29"
env_logger = "0.11.8"

tracing = { version = "0.1.43", features = ["log-always"] }
sourceview5 = "0.10.0"
libspelling = { version = "0.4.1", optional = true }
blurhash = { git = "https://github.com/Schmiddiii/blurhash-rs", rev = "a46af692e783f81f4ac752c91ef13847521c5352", features = ["gdk-pixbuf"] }
image = "0.25.9"
chrono = "0.4.42"

phonenumber = { version = "0.3", optional = true }

# To speed up startup on dev builds, build some crypto crates in release mode.
[profile.dev.package.sqlcipher-crypto-provider]
opt-level = 3
[profile.dev.package.pbkdf2]
opt-level = 3
[profile.dev.package.hmac]
opt-level = 3
[profile.dev.package.cbc]
opt-level = 3
[profile.dev.package.aes]
opt-level = 3
[profile.dev.package.sha1]
opt-level = 3
[profile.dev.package.sha2]
opt-level = 3

[features]
default = []
cacao-gui = [ "dep:cacao", "dep:objc", "dep:objc_id" ]
screenshot = [ "dep:phonenumber" ]
screenshot-setup = [ "screenshot" ]
libspelling = [ "dep:libspelling" ]

[patch.crates-io]
curve25519-dalek = { git = 'https://github.com/signalapp/curve25519-dalek', tag = 'signal-curve25519-4.1.3' }
